"""Schemas for structured data."""
from flatland.util.deferred import deferred_module


deferred_module.shadow(
    'flatland',
    {'exc': ('AdaptationError',),
     'schema': ('Array',
                'Boolean',
                'Compound',
                'Constrained',
                'Container',
                'Date',
                'DateTime',
                'DateYYYYMMDD',
                'Decimal',
                'Dict',
                'Element',
                'Enum',
                'Float',
                'Form',
                'Integer',
                'JoinedString',
                'List',
                'Long',
                'Mapping',
                'MultiValue',
                'Number',
                'Ref',
                'Scalar',
                'Sequence',
                'Skip',
                'SkipAll',
                'SkipAllFalse',
                'String',
                'Time',
                'Unevaluated',
                ),
     'signals': (),
     'util': ('Unspecified', 'class_cloner',),
     'validation': (),
     },
    __version__='dev')
